// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"blog-grpc-microservices/api/protobuf/comment/v1"
	"blog-grpc-microservices/internal/comment"
	"blog-grpc-microservices/internal/pkg/config"
	"blog-grpc-microservices/internal/pkg/dbcontext"
	"blog-grpc-microservices/internal/pkg/log"
)

// Injectors from wire.go:

func InitServer(logger *log.Logger, conf *config.Config) (v1.CommentServiceServer, error) {
	db, err := dbcontext.NewCommentDB(conf)
	if err != nil {
		return nil, err
	}
	repository := comment.NewRepository(logger, db)
	commentServiceServer := comment.NewServer(logger, repository)
	return commentServiceServer, nil
}
